# Generated by Django 5.1.1 on 2024-10-08 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('job_tybe', models.CharField(choices=[('full time', 'full time'), ('part time', 'part time')], max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('experience', models.IntegerField(default=1)),
                ('published_at', models.DateField(auto_now=True)),
                ('vacancy', models.IntegerField(default=1)),
                ('salary', models.IntegerField(default=1)),
                ('category', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='job.category')),
            ],
        ),
    ]
