# Generated by Django 5.1 on 2024-10-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
