# Generated by Django 5.1 on 2024-10-08 19:44

import job.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_job_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_image',
            field=models.ImageField(default='', upload_to=job.models.upload_image),
            preserve_default=False,
        ),
    ]
