# Generated by Django 5.1 on 2024-10-08 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_job_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_image',
            new_name='image',
        ),
    ]
