# Generated by Django 5.1 on 2024-10-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_rename_job_image_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='sulg',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
