# Generated by Django 5.1 on 2024-10-13 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_sulg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='sulg',
            new_name='slug',
        ),
    ]
