# Generated by Django 5.1 on 2024-10-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_rename_sulg_job_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.TextField()),
                ('cv', models.FileField(upload_to='apply/')),
                ('cover', models.TextField()),
                ('published', models.DateField(auto_now=True)),
            ],
        ),
    ]
