# Generated by Django 5.1 on 2024-10-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_apply_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='website',
            field=models.URLField(),
        ),
    ]
